sonar.projectKey=Releases-Notes-Board
sonar.projectName=Releases-Notes-Board
sonar.sources=src
sonar.java.binaries=target/classes
sonar.java.libraries=target/sonar-java-libraries
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=src/test/**/*,\
  src/main/java/com/dbcargo/notesboard/NotesboardApplication.java,\
  src/main/java/com/dbcargo/notesboard/validations/**,\
sonar.java.coveragePlugin=jacoco