CREATE TABLE application (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50)  NOT NULL
);

CREATE TABLE item (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(100) NOT NULL
);